sudo: required
services:
  - docker

before_install:
  - docker build -t kc88998899889988/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kc88998899889988/react-test npm run test -- --coverage

language: generic

after_success:
  - docker build -t kc88998899889988/multi-client ./client
  - docker build -t kc88998899889988/multi-nginx ./nginx
  - docker build -t kc88998899889988/multi-server ./server
  - docker build -t kc88998899889988/multi-worker ./worker
  #
  # Log in to the docker CLI
  #
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  #
  # take those images and push them into DockerHub
  #
  - docker push kc88998899889988/multi-client
  - docker push kc88998899889988/multi-nginx
  - docker push kc88998899889988/multi-server
  - docker push kc88998899889988/multi-worker
